### PR TITLE
Upgrade System.Text.Json to 5.0.0-rc.2.20475.5

### PR DESCRIPTION
**Pull request by klimisa**
Upgraded `System.Text.Json` to the current latest (5.0.0-rc.2.20475.5) and fixed failing tests. 

Because the tests in `FsCodec.SystemTextJson.Tests` were failing with the following error,

```
System.IO.FileNotFoundException
Could not load file or assembly 'System.Text.Encodings.Web, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

I had to explicitly add a reference to `System.Text.Encodings.Web` under `5.0.0-rc.2.20475.5`.

### CODE REVIEW

**Comment by bartelink** [comment]
Thanks! 

Aside: I've just discovered I pushed https://github.com/jet/FsCodec/commit/11a840d9a5dedc0b96f901b94c29169fcd0ecb90

Does this resolve the FSI issue you mentioned out of band (perhaps an explicit `#r "System.Text.Encodings.Web"` might help )?

May I also ask you to add a line to changelog.md (Under Unreleased) please?

**Comment by bartelink** [comment]
Just tried it now, and still seeing (in Rider 2020.1.2's FSI):

```
Microsoft (R) F# Interactive version 10.7.0.0 for F# 4.7

...

error FS0193: Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
```

That tallies with what I saw with RC1.

Given this adds a dependency on Prerelease packages, I'm not sure merging it to `master` makes sense yet until we understand why?

**Comment by klimisa** [comment]
Yes @bartelink, it makes sense to keep it open until we understand what causes the issue.

**Comment by bartelink** [comment]
I'm wondering whether the `#r "nuget:` technique in https://github.com/jet/equinox/pull/262 (and/or reordering the references) might help here...

**Comment by klimisa** [comment]
Replaced everything to be taken from NuGet but still doesn't work. 

```
module Contract =

    type Item = { value : string option }
    // implies default options from Options.Create(), which includes OptionConverter
    let serialize (x : Item) : string = FsCodec.SystemTextJson.Serdes.Serialize x
    // implies default options from Options.Create(), which includes OptionConverter
    let deserialize (json : string) = FsCodec.SystemTextJson.Serdes.Deserialize json

Binding session to '/home/klimisa/.nuget/packages/fscodec.systemtextjson/2.1.1/lib/netstandard2.1/FsCodec.SystemTextJson.dll'...
Binding session to '/home/klimisa/.nuget/packages/system.text.json/5.0.0/lib/netcoreapp3.0/System.Text.Json.dll'...


error FS0193: Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.



error FS0193: Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

Btw the sample you posted uses `FsCodec.NewtonsoftJson` which works fine.

**Comment by bartelink** [comment]
I guess it makes sense to get off beta packages either way; if you update the reference to 5.0.0, I'll merge it, regardless of whether we can figure out the fsi issues?

**Comment by bartelink** [comment]
I guess this can be closed now?

**Pull request closed without merging**
