### PR TITLE
Target System.Text.Json 5.0.0 final

### PR DESCRIPTION
**Pull request by bartelink**
Update `FsCodec.SystemTextJson` to use `5.0.0` final
Updated build and projects to rely on `5.0.200` SDK (local build works on my Mac from command line and Rider with only that)

### CODE REVIEW

**Comment by bartelink** [comment]
@klimisa I have no idea what I did, but it seems this works in latest Rider on a Mac with only the 5.0 SDK installed
I've killed an old branch I had; Probably best to close #56 now ? (if you have time, would be good to check it's all happy of course!)

**Comment by klimisa** [comment]
Let me have a look now!

PS: sorry for not being active, it have been a busy and it's still is.

**Comment by klimisa** [comment]
All works fine on Linux!!!

Rider : 
image

Shell:
image


cc/ @bartelink

**Comment by bartelink** [comment]
Thanks for validating @klimisa 
Will merge now.

I'm thinking I'll release it as V 2.2.1, though arguably it merits a bigger increment I guess it definitely will when I get bored of looking at #59 :D

**Pull request merged**
